quarkus:
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      methods: GET,POST
      origins: "/.*/"
    port: 8080

  container-image:
    group: openepcis
    name: testdata-generator
    additional-tags:
      - latest

  native:
    additional-build-args: "--initialize-at-run-time=org.apache.commons.math3.random.RandomDataGenerator\\,io.openepcis.testdata.generator.format.RandomValueGenerator"
    resources:
      includes: static/**,static-web/**

mp:
  openapi:
    filter: "io.openepcis.testdata.api.filter.SchemaExampleOASFilter"