quarkus:
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      methods: GET,POST
      origins: "/.*/"
    port: 8080

  container-image:
    group: openepcis
    name: testdata-generator
    additional-tags:
      - latest

  locales: en
  default-locale: en-US
  native:
#    additional-build-args: "--trace-object-instantiation=java.security.SecureRandom,-H:+UnlockExperimentalVMOptions,--initialize-at-run-time=org.eclipse.persistence.sessions.coordination.DiscoveryManager\\,org.eclipse.persistence.eis.EISLogin\\,org.eclipse.persistence.asm.internal.platform.ow2.SerialVersionUIDAdderImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.ClassReaderImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.TypeImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.LabelImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.ClassWriterImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.AnnotationVisitorImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.FieldVisitorImpl\\,org.eclipse.persistence.asm.internal.platform.ow2.MethodVisitorImpl\\,org.eclipse.persistence.eis.EISConnectionSpec\\,org.eclipse.persistence.eis.EISPlatform\\,org.eclipse.persistence.sessions.coordination.RemoteCommandManager\\,sun.rmi.transport.DGCImpl\\,org.eclipse.persistence.sessions.coordination.jms.JMSPublishingTransportManager\\,org.eclipse.persistence.internal.sessions.coordination.jms.JMSTopicRemoteConnection\\,io.openepcis.epc.converter.common.VersionTransformerProducer\\,org.apache.commons.math3.random.RandomDataGenerator\\,org.eclipse.persistence.sessions.coordination.broadcast.BroadcastTransportManager\\,io.openepcis.testdata.generator.format.RandomValueGenerator,-H:-LocalizationOptimizedMode,-Duser.country=US,-Duser.language=en,-H:IncludeLocales=en,-H:IncludeResourceBundles=jakarta.xml.bind.Messages,-H:ReflectionConfigurationFiles=reflection-config.json,-H:-UnlockExperimentalVMOptions"
    additional-build-args: "--trace-object-instantiation=java.security.SecureRandom,-H:+UnlockExperimentalVMOptions,--initialize-at-build-time=org.eclipse.persistence.jaxb,--initialize-at-build-time=org.eclipse.persistence.oxm,--initialize-at-run-time=io.openepcis.epc.converter.common.VersionTransformerProducer\\,org.apache.commons.math3.random.RandomDataGenerator\\,io.openepcis.testdata.generator.format.RandomValueGenerator,-H:-LocalizationOptimizedMode,-Duser.country=US,-Duser.language=en,-H:IncludeLocales=en,-H:IncludeResourceBundles=jakarta.xml.bind.Messages,-H:ReflectionConfigurationFiles=reflection-config.json,-H:-UnlockExperimentalVMOptions"
    resources:
      includes: static/**,static-web/**,jakarta/**/*.properties,**/jaxb.properties,META-INF/services/.*,META-INF/.*.kotlin_module$
  banner:
    path: "openepcis-banner.txt"
  package:
    type: "uber-jar"


mp:
  openapi:
    filter: "io.openepcis.testdata.api.filter.SchemaExampleOASFilter"

    extensions:
      smallrye:
        info:
          title: "OpenEPCIS Test Data Generator API"
          version: "1.0.0"
          description: "Generate test data events quickly by providing an event generation model to the simulation engine."
          contact:
            email: "info@openepcis.io"
            name: "OpenEPCIS | benelog GmbH & Co. KG"
            url: "https://openepcis.io"
            license:
              name: "Apache 2.0"
              url: "http://www.apache.org/licenses/LICENSE-2.0.html"
